import Link from 'next/link';
// import './globals.css';
import 'tailwindcss/tailwind.css';
import NavLink from './nav-link';

export default function RootLayout({ 
   //default components in next 13 are React server components
  children,
}: {
  children: React.ReactNode;
}) {
  console.log('render')

  return (
    <html lang="en" className='bg-gray-900 text-gray-100' >
      <head>
        <title>First Next13 App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <body>
        <header className='border-b p-4'>
          <nav className='space-x-4'>
            <NavLink href='/'>Home</NavLink>
            <NavLink href='/movies'>Movies</NavLink>
          </nav>
        </header>

        <div className="p-4">{children}</div>
      </body>
    </html>
  );
}
